name: Build
on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build library
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Configure gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build everything
        working-directory: MarkdownView
        run: ./gradlew assemble
